spring:
  application:
    name: commerceapi
  datasource:
    url: jdbc:sqlite:./data/app.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      init:
        mode: always

jwt:
  secret: dGhpcy1pcy1hLXNlY3JldC1rZXktd2l0aC0zMi1ieXRlcy1mb3Itand0LWNvcnJlY3QteWVz
  expiration: 86400000