-- Initial schema for PostgreSQL, generated from the JPA entity model.
-- Baseline version for existing databases created with ddl-auto=update.

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    email varchar(255) NOT NULL,
    password_hash varchar(255),
    user_role varchar(255) NOT NULL CHECK (user_role IN ('CUSTOMER', 'ADMIN', 'STOREOWNER')),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    street varchar(255) NOT NULL,
    number varchar(255),
    city varchar(100) NOT NULL,
    state varchar(2) NOT NULL,
    zip_code varchar(10) NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    display_name varchar(100) NOT NULL,
    description varchar(500) NOT NULL,
    active boolean NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE stores (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    slug varchar(100) NOT NULL,
    email varchar(100) NOT NULL,
    active boolean NOT NULL,
    store_owner_id bigint,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id),
    CONSTRAINT uk_stores_slug UNIQUE (slug),
    CONSTRAINT uk_stores_email UNIQUE (email),
    CONSTRAINT uk_stores_store_owner UNIQUE (store_owner_id),
    CONSTRAINT fk_stores_store_owner FOREIGN KEY (store_owner_id) REFERENCES users (id)
);

CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(200) NOT NULL,
    description varchar(2000),
    price numeric(10, 2) NOT NULL,
    active boolean NOT NULL,
    category_id bigint NOT NULL,
    store_id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_products_store FOREIGN KEY (store_id) REFERENCES stores (id)
);

CREATE TABLE stocks (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    quantity integer NOT NULL,
    reserved integer NOT NULL,
    last_updated timestamp,
    product_id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id),
    CONSTRAINT uk_stocks_product UNIQUE (product_id),
    CONSTRAINT fk_stocks_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint NOT NULL,
    store_id bigint NOT NULL,
    status varchar(20) NOT NULL CHECK (status IN ('CREATED', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELED')),
    date timestamp NOT NULL,
    total numeric(10, 2) NOT NULL,
    street varchar(255) NOT NULL,
    number varchar(255),
    city varchar(100) NOT NULL,
    state varchar(2) NOT NULL,
    zip_code varchar(10) NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users (id),
    CONSTRAINT fk_orders_store FOREIGN KEY (store_id) REFERENCES stores (id)
);

CREATE TABLE order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id bigint NOT NULL,
    method varchar(20) NOT NULL CHECK (method IN ('CREDIT_CARD', 'PIX', 'BOLETO')),
    status varchar(20) NOT NULL CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'CANCELED')),
    amount numeric(10, 2) NOT NULL,
    transaction_id varchar(64) NOT NULL,
    checkout_url varchar(255),
    paid_at timestamp,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    PRIMARY KEY (id),
    CONSTRAINT uk_payments_transaction_id UNIQUE (transaction_id),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id)
);
